stoplightio/stoplight.io

app/_assets/stylesheets/_navbar.scss, app/_assets/stylesheets/_typography.scss, app/_assets/stylesheets/styles.scss
The expanded type caused some spacing issues on the nav bar. Adjusted the padding to account for wider text blocks. These changes only affect Safari, Firefox and Chrome.
Here is [an image](https://drive.google.com/file/d/0Bweykl5-b4nVTHljUFhHY29xdHM/view) that shows the before and after.
=> BZ1 slight typographic update

netlify/pages/about.yaml
=> Update Pages “about” (#163)

netlify/pages/about.yaml
=> Update Pages “about” (#165)

netlify/blog-posts/open-banking-regulation-and-api-design.md
=> Update Blog Post “open-banking-regulation-and-api-design” (#660)

netlify/blog-posts/example.md
=> Update Blog Post “Fundamentals of API Unit Testing"

netlify/forms/contact-us.yaml, netlify/forms/request-demo.yaml, netlify/lists/blog.yaml, netlify/lists/case-studies.yaml, netlify/pages/about.yaml, netlify/pages/pricing.yaml, netlify/subpages/api-design-guide-oas-spec.md, netlify/subpages/api-design-guide-tooling.md, netlify/subpages/api-design-guide.md, netlify/subpages/api-documentation-guide-advanced.md, netlify/subpages/api-documentation-guide-best-practices.md, netlify/subpages/api-documentation-guide.md, netlify/subpages/documentation-enterprise.md, netlify/subpages/documentation-helper.md, netlify/subpages/policy.md, netlify/subpages/privacy.md, netlify/subpages/terms.md
=> fix: added meta descriptions

public/_redirects, static.config.js
=> Feat seo redirects and fixes

netlify/landings/design.yaml, netlify/landings/docs.yaml, netlify/landings/mocking.yaml, netlify/landings/testing.yaml, netlify/subpages/api-design-guide-tooling.md, netlify/subpages/api-documentation-guide-advanced.md, netlify/subpages/api-documentation-guide.md, netlify/subpages/mock-api-server-guide-advanced.md, netlify/subpages/mock-api-server-guide.md, public/_redirects
Content & Link structure for @tbarn to review
=> Link structure & Mocking Guide update

netlify/forms/request-demo.yaml, netlify/lists/case-studies.yaml, netlify/subpages/api-documentation-guide.md
Making the changes that didn't get made the other week
=> Meta description

netlify/blog-posts/stoplight-v4-9-0-release.md
=> Update Blog Post “stoplight-v4-9-0-release” (#755)

netlify/blog-posts/what-is-the-meaning-of-api-testing.md
=> Update Blog Post “what-is-the-meaning-of-api-testing” (#767)

package.json, src/components/Header/index.tsx, src/styles/app.scss, yarn.lock
This adds additional top level header link property className.
Sign In/Sign Up link text change is a impure hack in Header component. 
IMO, there is no clean way to drive it from configuration.
\cc @moaiandin
=> feat: sticky header and changeable Sign In link

netlify/blog-posts/introducing-spectral.md, netlify/settings.yaml, package.json, src/components/Header/Desktop.tsx, src/components/Header/Mobile.tsx, src/components/Header/config.js, src/components/Header/index.tsx, src/components/Hero/index.tsx, src/styles/app.scss, yarn.lock
=> New sticky header!

netlify/pages/pricing.yaml
Force merge of:
* "netlify/pages/pricing.yaml"
=> Deletion of Extra Column. Automatically generated. Merged on Netlify CMS

netlify/landings/prism.yaml, netlify/landings/spectral.yaml
Now that Spectral and Prism have docs we should show them off.
=> feat: link to our lovely new docs

netlify/landings/hubs.yaml
=> chore: update hubs CTA text

netlify/landings/studio.yaml, netlify/pages/enterprise.yaml, netlify/settings.yaml, src/components/Header/index.tsx
- fixes https://github.com/stoplightio/stoplight.io/issues/1122
=> Add Changelog v1.1.0 to blog 

netlify/landings/mocking.yaml, netlify/landings/studio.yaml, netlify/settings.yaml, netlify/subpages/api-design-guide-openapi.md, netlify/subpages/design-free.md, netlify/subpages/mock-api-server-guide-advanced.md, netlify/subpages/mocking-server.md, netlify/subpages/testing-enterprise.md, netlify/subpages/testing-integration.md
Please merge after PR checks have passed
=> Deploy to production

netlify/forms/request-demo.yaml
Need to revert until we can get the form to appear above the fold when left content is present.
=> Revert Changes to Demo Form

netlify/pages/about.yaml
Remove Duane & Mateusz
Add Dave
Change Ross' title
=> Update /about with team changes
